### ISSUE TITLE
Add alignment emojis

### ISSUE THREAD

**Issue by shellychw** [lwise/meowbot#2]
Setup the good, evil, lawful, and chaotic emojis in the discord server.

**Comment by lwise** [comment]
![656928547293626391](https://user-images.githubusercontent.com/13436240/97058620-53152000-155c-11eb-8a32-50a4ec4aa19d.png)
![720225226377396254](https://user-images.githubusercontent.com/13436240/97058623-56101080-155c-11eb-9777-3a36d79e3d6d.png)

Lawful and Good chosen and added

**Comment by lwise** [comment]
![494901835686215680-2](https://user-images.githubusercontent.com/13436240/97063073-beb2b980-156b-11eb-9bb9-255e6e5550dd.png)
Chaotic chosen and added

**Comment by lwise** [comment]
![BlobKittenKnife](https://user-images.githubusercontent.com/13436240/97063368-56fd6e00-156d-11eb-848c-9336a14470e8.png)
Evil chosen and added
