### ISSUE TITLE
Ask Meowbot Questions

### ISSUE THREAD

**Issue by shellychw** [lwise/meowbot#23]
### What is the feature to be added?
Ask meowbot a question and to get an answer!

### Why?
Because it would be cute <3 

Requested by: shelly

#### Notes:

- The message should start with the word "Meowbot" and end with a question mark (?)
- Meowbot can reply with a fortune cookie quote
- possible source http://www.fortunecookiemessage.com/

**Comment by lwise** [comment]
oh we did this #45
