### ISSUE TITLE
Have meowbot store a list of upcoming events

### ISSUE THREAD

**Issue by lwise** [lwise/meowbot#39]
### What is the feature to be added?

I haven't thought about the details too hard but:
- Give meowbot a command like `m!event <name> <date> <time> <description> <channel>` and MeowBot will store it in the events list.
- You can check for upcoming events with `m!events`... maybe which ones show up depend on which channel you sent it in? Or maybe it's limited by role. Some kind of way to have private events too. (If we think this is needed. Maybe it can be a later enhancement.)
- Meowbot can then remind you of the event day-of or day-before or something.

### Why?

Nice way to set things up.

**Comment by shellychw** [comment]
This overlaps with #14 and #18 I mean I haven't thought those through yet so we can just remove it.
The idea is that we can use those events to say happy birthday to people too.
